version: build.{build}
image: Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - nuget restore
build:
  verbosity: normal
#after_build:
#  - ps: .\package-ERMine.ps1
#artifacts:
#  - path: ERMine.Core\bin\Debug
#    name: Framework
#  - path: ERMine.Drawing\bin\Debug
#    name: Drawing-CLI
#  - path: .nupkg\*.nupkg
#    name: Nuget package
#deploy:
#  - provider: NuGet
#    api_key:
#      secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
#    on:
#      APPVEYOR_REPO_TAG: true
#  - provider: GitHub
#    tag: $(APPVEYOR_REPO_TAG_NAME)
#    release: $(APPVEYOR_REPO_TAG_NAME)
#    auth_token:
#      secure: gTGqBBhf3S0Lsk7Xd0pY4Iu2s53Cnwylt/fqlviT2s/wsabO4RALF5wcDFAIM+XY
#    artifact: Framework
#    draft: true
#    on:
#      APPVEYOR_REPO_TAG: true